export const INITIAL_JOBS = [
  {
    id: 'job-101',
    name: 'Granilla Reklama',
    client: 'Filmová Produkce',
    assignedGaffer: 'Petr M.',
    riggingDate: '2026-08-24',
    deriggingDate: '2026-08-25',
    status: 'ACTIVE',
    mode: 'LOADING',
  },
  {
    id: 'job-102',
    name: 'Reklama Škoda – Den 2',
    client: 'Škoda Auto / Bistro Films',
    assignedGaffer: 'Petr M.',
    riggingDate: '2026-08-24',
    deriggingDate: '2026-08-24',
    status: 'ACTIVE',
    mode: 'LOADING',
  },
  {
    id: 'job-103',
    name: 'Film: Shadows of Prague',
    client: 'Barrandov Studios',
    assignedGaffer: 'Jan K.',
    riggingDate: '2026-08-28',
    deriggingDate: '2026-08-28',
    status: 'ACTIVE',
    mode: 'DERIGGING',
  },
  {
    id: 'job-104',
    name: 'Vodafone TV Spot - Archiv',
    client: 'Vodafone CZ',
    assignedGaffer: 'Petr M.',
    riggingDate: '2026-08-10',
    deriggingDate: '2026-08-11',
    status: 'ARCHIVED',
    mode: 'LOADING',
  }
];

export const INITIAL_JOB_ITEMS = [
  {
    id: 'ji-001',
    jobId: 'job-101',
    catalogId: 'cat-1',
    name: 'ARRI SkyPanel S60-C',
    category: 'Lights',
    assignedVehicleId: 'v1',
    quantityRequested: 2,
    quantityLoaded: 2,
    status: 'LOADED',
    serialNumber: 'ASK-S60-304',
    isAdHoc: false,
    damageNotes: '',
    photoUrls: ['https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=600&q=80'],
  },
  {
    id: 'ji-002',
    jobId: 'job-101',
    catalogId: 'cat-2',
    name: 'Aputure LS 600d Pro',
    category: 'Lights',
    assignedVehicleId: 'v1',
    quantityRequested: 2,
    quantityLoaded: 2,
    status: 'LOADED',
    serialNumber: 'AP-600D-555, AP-600D-400',
    isAdHoc: false,
    damageNotes: '',
    photoUrls: ['https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=600&q=80'],
  },
  {
    id: 'ji-003',
    jobId: 'job-101',
    catalogId: 'cat-3',
    name: 'C-Stand 40" Turtle Base',
    category: 'Grip',
    assignedVehicleId: 'v1',
    quantityRequested: 6,
    quantityLoaded: 0,
    status: 'PENDING',
    serialNumber: 'CST-40-101',
    isAdHoc: false,
    damageNotes: '',
    photoUrls: ['https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?auto=format&fit=crop&w=600&q=80'],
  },
  {
    id: 'ji-004',
    jobId: 'job-101',
    catalogId: 'cat-4',
    name: 'Kabel 400V 32A 25m Heavy Duty',
    category: 'Cables',
    assignedVehicleId: 'v1',
    quantityRequested: 4,
    quantityLoaded: 0,
    status: 'PENDING',
    serialNumber: 'CBL-32A-25',
    isAdHoc: false,
    damageNotes: '',
    photoUrls: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80'],
  },
  {
    id: 'ji-005',
    jobId: 'job-101',
    catalogId: 'cat-5',
    name: 'Rozvaděč 63A -> 6x 32A / 12x 230V',
    category: 'Distribution',
    assignedVehicleId: 'v1',
    quantityRequested: 1,
    quantityLoaded: 0,
    status: 'PENDING',
    serialNumber: 'DIST-63A-01',
    isAdHoc: false,
    damageNotes: '',
    photoUrls: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80'],
  },
  {
    id: 'ji-006',
    jobId: 'job-101',
    catalogId: 'cat-6',
    name: 'Rám 12x12ft s Difúzní Látkou (Full Grid)',
    category: 'Textiles',
    assignedVehicleId: 'v1',
    quantityRequested: 1,
    quantityLoaded: 0,
    status: 'PENDING',
    serialNumber: 'TXT-12X12-FG',
    isAdHoc: false,
    damageNotes: '',
    photoUrls: ['https://images.unsplash.com/photo-1585336261026-870a6d216b54?auto=format&fit=crop&w=600&q=80'],
  },
  {
    id: 'ji-007',
    jobId: 'job-101',
    catalogId: 'cat-7',
    name: 'Balast ARRI EB MAX 1.8kW',
    category: 'Ballasts',
    assignedVehicleId: 'v1',
    quantityRequested: 1,
    quantityLoaded: 0,
    status: 'PENDING',
    serialNumber: 'BLST-MAX-18',
    isAdHoc: false,
    damageNotes: '',
    photoUrls: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80'],
  }
];

export const INITIAL_VEHICLES = [
  { id: 'v1', name: 'Mercedes Sprinter (Gaffer Van)', licensePlate: '5A1 2345', capacityWeight: '3.5 t' },
  { id: 'v2', name: 'MAN TGL 12t (Grip Truck)', licensePlate: '9B2 9876', capacityWeight: '12 t' },
];

export const INITIAL_CONSUMABLES = [
  { id: 'c1', name: 'Gaffa Páska Černá 50mm x 50m', category: 'Pásky', state: 0, stateLabel: 'OK' },
  { id: 'c2', name: 'Gaffa Páska Stříbrná 50mm', category: 'Pásky', state: 1, stateLabel: '50%' },
  { id: 'c3', name: 'Papírová Páska 25mm (Black)', category: 'Pásky', state: 0, stateLabel: 'OK' },
  { id: 'c4', name: 'Baterie 9V PP3 Industrial', category: 'Baterie', state: 2, stateLabel: 'REFILL' },
  { id: 'c5', name: 'Baterie AA Varta Industrial (box 20ks)', category: 'Baterie', state: 1, stateLabel: '50%' },
  { id: 'c6', name: 'Čistič na optiku & filtry isopropyl', category: 'Čištění', state: 0, stateLabel: 'OK' },
  { id: 'c7', name: 'Mikrovláknové utěrky pack', category: 'Čištění', state: 2, stateLabel: 'REFILL' },
  { id: 'c8', name: 'Elektrikářská páska izolační černá', category: 'Drobný materiál', state: 0, stateLabel: 'OK' },
];

export const INITIAL_AUDIT_LOGS = [
  {
    id: 'log-1',
    timestamp: '2026-08-21T19:30:00Z',
    user: 'Petr M. (Lead Gaffer)',
    jobId: 'job-101',
    action: 'Přidáno z katalogu',
    detail: 'Vloženo ARRI SkyPanel S60-C (2 ks) do zakázky Granilla Reklama',
    type: 'add',
  },
  {
    id: 'log-2',
    timestamp: '2026-08-21T19:40:00Z',
    user: 'Petr M. (Lead Gaffer)',
    jobId: 'job-101',
    action: 'Přičtení kusů',
    detail: 'Aputure LS 600d Pro: 2/2 ks naloženo na place',
    type: 'loaded',
  }
];

export const INITIAL_CATALOG = [
  {
    id: 'cat-1',
    name: 'ARRI SkyPanel S60-C',
    category: 'Lights',
    weight: '28 lbs',
    power: '450W LED',
    image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=600&q=80',
    serialPrefix: 'ASK-S60',
    availableCount: 8,
    isBundle: false,
  },
  {
    id: 'cat-2',
    name: 'Aputure LS 600d Pro',
    category: 'Lights',
    weight: '11 lbs',
    power: '720W COB',
    image: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=600&q=80',
    serialPrefix: 'AP-600D',
    availableCount: 12,
    isBundle: false,
  },
  {
    id: 'cat-3',
    name: 'C-Stand 40" Turtle Base',
    category: 'Grip',
    weight: '16 lbs',
    power: 'N/A (Grip)',
    image: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?auto=format&fit=crop&w=600&q=80',
    serialPrefix: 'CST-40',
    availableCount: 30,
    isBundle: false,
  },
  {
    id: 'cat-4',
    name: 'Kabel 400V 32A 25m Heavy Duty',
    category: 'Cables',
    weight: '22 lbs',
    power: '32A / 400V',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    serialPrefix: 'CBL-32A',
    availableCount: 15,
    isBundle: false,
  },
  {
    id: 'cat-5',
    name: 'Rozvaděč 63A -> 6x 32A / 12x 230V',
    category: 'Distribution',
    weight: '35 lbs',
    power: '63A Master',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    serialPrefix: 'DIST-63A',
    availableCount: 5,
    isBundle: false,
  },
  {
    id: 'cat-6',
    name: 'Rám 12x12ft s Difúzní Látkou',
    category: 'Textiles',
    weight: '18 lbs',
    power: 'N/A (Textil)',
    image: 'https://images.unsplash.com/photo-1585336261026-870a6d216b54?auto=format&fit=crop&w=600&q=80',
    serialPrefix: 'TXT-12X12',
    availableCount: 6,
    isBundle: false,
  },
  {
    id: 'cat-7',
    name: 'Balast ARRI EB MAX 1.8kW',
    category: 'Ballasts',
    weight: '14 lbs',
    power: '1800W High Speed',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    serialPrefix: 'BLST-1800',
    availableCount: 10,
    isBundle: false,
  },
  {
    id: 'cat-8',
    name: 'ARRI SkyPanel S30-C Complete Kit',
    category: 'Kits',
    weight: '42 lbs',
    power: '200W Kit',
    image: 'https://images.unsplash.com/photo-1585336261026-870a6d216b54?auto=format&fit=crop&w=600&q=80',
    serialPrefix: 'KIT-S30',
    availableCount: 4,
    isBundle: true,
    bundleItems: [
      { name: 'ARRI SkyPanel S30-C Head', qty: 1 },
      { name: 'S30 Power Supply Unit', qty: 1 },
      { name: 'DC Cable 3m', qty: 1 },
      { name: 'DoPchoice Snapgrid 40°', qty: 1 },
      { name: 'Transportní kufry Heavy', qty: 1 },
    ],
  }
];
